# Generated by Django 2.2 on 2019-04-07 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Webmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client_user_agent', models.CharField(max_length=255)),
                ('client_ip', models.CharField(max_length=255)),
                ('client_country', models.CharField(max_length=255)),
                ('client_timezone', models.CharField(max_length=255)),
                ('client_city', models.CharField(max_length=255)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redirect_app.Offer')),
                ('webmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redirect_app.Webmaster')),
            ],
        ),
    ]
